applications:
  echo_app:
    name: Echo App
    description: A simple Python echo app
    working_directory: examples
    interpreter_type: python
    command: echo.py
    env_vars:
      PORT: "8888"
   
  hello_app:
    name: Hello World
    description: A simple Node.js hello world server
    working_directory: examples
    interpreter_type: python
    command: hello.py
    env_vars:
      PORT: "8889"
      NODE_ENV: development
    
deployment_mode: local

# Docker configuration (uncomment to use Docker deployment)
# deployment_mode: docker
# docker_config:
#   base_image: python:3.11-slim
#   network: bridge
#   volumes:
#     ./examples: /app/examples 